# Generated by Django 4.2.3 on 2023-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HM', 'Hospital Manager'), ('GU', 'Guest')], max_length=20),
        ),
    ]
