# Generated by Django 4.2.3 on 2023-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_service_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
